added item and users features
AkhmTimur/java-shareit pull request #1
Opened 2022-12-25 15:16 UTC by AkhmTimur

2022-12-27 23:45 UTC, NikolaiDem requested changes

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    private final Map<Integer, Integer> itemUser = new HashMap<>();
Какой профит использования такой мапы?

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    public Item createItem(Item item, Integer userId) {
В метод сервиса должен передаться DTO (ItemDto), а сервис преобразует его в бизнес объект (Item) с помощью маппера и выполняет с ними операции.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (item.getAvailable() != null &&
Если на Dto навешаны аннотации валидации, то такие проверки излишни.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (Objects.equals(itemUser.get(item.getId()), userId)) {
Лучше добавить владельца в вещь Item, тогда можно проверить, является ли пользователь владельцем без дополнительной мапы.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +                if (item.getAvailable() && item.getDescription().toLowerCase().contains(searchCriteria.toLowerCase())) {
Поиск выполняется не только в описании, но и в названии тоже.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") Integer userId, @RequestBody @Valid Item item) {
Контроллер работает только с Dto, как получает, так и отправляет. Аналогично для остальных методов.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestBody @Valid Item item) {
Здесь @Valid лишний, потому что при патче может обновляться только одно или несколько полей, остальные поля в объекте могут быть null.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Boolean available;
Еще владельца можно добавить.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        if (user.getEmail() != null) {
Можно воспользоваться аннотацией @Email для автоматической валидации.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +    public User addToUsers(User user) {
Метод сервиса должен получать UserDto из контроллера. Аналогично для остальных методов.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
Code Style : удалить лишние пустые строки.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User createUser(@Valid @RequestBody User user) {
Методы контроллера работают только с Dto (UserDto). Аналогично для остальных методов.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User updateUser(@PathVariable Integer userId, @Valid @RequestBody User user) {
@Valid здесь лишний.

2022-12-27 23:45 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email
Аннотации валидации должны быть в объектах Dto.

2022-12-28 02:15 UTC, AkhmTimur commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    private final Map<Integer, Integer> itemUser = new HashMap<>();
Решил сделать такую мапу, чтобы проще было переходить на базу, тк можно скопировать часть функций.

2022-12-28 02:33 UTC, AkhmTimur commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (item.getAvailable() != null &&
А у меня к модели же привязаны не только операции создания, но и обновления, а там передаются только некоторые параметры.
![image](https://user-images.githubusercontent.com/104717634/209748139-f61138da-0c8a-4088-8129-884f62a5460f.png)
Например вот, тут если бы были аннотации то тесты сваливался с ошибкой.

2022-12-28 03:43 UTC, AkhmTimur commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        if (user.getEmail() != null) {
Николай, подскажи, пожалуйста,  как тут действовать не понимаю как тут это применить. У меня аннотация email уже для юзера есть, но при проверке ничего происходит. Тест сваливается с ошибкой и все

2022-12-28 22:10 UTC, NikolaiDem requested changes

2022-12-28 22:10 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            if (item.getOwnerId().equals(userId)) {
Вместо мапы, где был указан юзер по вещи, лучше использовать мапу, где ключ - это userId, а значение - список его вещей. Тогда здесь не нужно перебирать все вещи каждый раз.

2022-12-28 22:10 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String name;
Так как в контроллере валидация есть, то лучше добавить NotBlank для name.

2022-12-28 22:10 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @Email
И еще лучше проверить на null, NotNull

2022-12-28 22:10 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        if (user.getEmail() != null) {
Какой тест падает?

2022-12-29 23:08 UTC, NikolaiDem approved these changes

2023-01-06 11:41 UTC, merged