added tests and pagination
AkhmTimur/java-shareit pull request #3
Opened 2023-01-30 10:16 UTC by AkhmTimur

2023-01-31 12:09 UTC, NikolaiDem requested changes

2023-01-31 12:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (from != null && size != null) {
Лучше в аргументах контроллера установить дефолтные значения вместо текущей проверки.

2023-01-31 12:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public boolean equals(Object o) {
А для чего здесь методы equals() и hashCode() переопределяются?
И в остальных dto.

2023-01-31 12:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestDto createItemRequest(@RequestHeader("X-Sharer-User-Id") Long userId,
Еще Valid для itemRequestDto?

2023-01-31 12:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    @Query(value = "select * from item_request where requester_id <> ?", nativeQuery = true)
Почему native?

2023-01-31 12:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +        if (itemRequestDto.getDescription() == null || itemRequestDto.getDescription().isBlank()) {
Можно использовать аннотацию NotBlank для itemRequestDto.

2023-01-31 12:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +            for (ItemDto itemDto : itemDtos) {
Здесь лучше использовать мапу со списком вещей по ключу запроса, чтобы избавиться от внутреннего цикла.

2023-01-31 12:09 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/bookings/controller/BookingControllerIT.java
> +package ru.practicum.shareit.bookings.controller;
Для всех модулей добавить еще json тесты и несколько интеграционных тестов.

2023-01-31 14:01 UTC, AkhmTimur commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (from != null && size != null) {
А как тогда проверять старые методы, где нет пагинации?

2023-02-01 17:38 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (from != null && size != null) {
Где проверять, какие методы?

2023-02-01 18:07 UTC, NikolaiDem requested changes

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        fromAndSizeCheck(from, size);
И пагинацию для запросов нужно реализовать.

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public List<BookingDto> getAllBookingsOwner(Long userId, String state, Integer from, Integer size) {
И пагинацию для запросов нужно реализовать.

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                  @RequestParam(name = "from", required = false) Integer from,
Лучше установить дефолтные значения вместо required - false. Тогда не понадобится дополнительная проверка.

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +    public List<ItemRequestDto> getItemRequests(Long userId) {
Запросы должны возвращаться в отсортированном порядке от более новых к более старым.

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +    public List<ItemRequestDto> getAllItemRequest(Long userId, Integer from, Integer size) {
Запросы сортируются по дате создания: от более новых к более старым.

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +        if (itemRequests.size() > 0) {
Это условие лишнее, стрим корректно отработает и для коллекции нулевой длины.

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +            if (items.containsKey(itemRequestDto.getId()) && items.get(itemRequestDto.getId()).size() > 0) {
Это условие лишнее items.get(itemRequestDto.getId()).size() > 0

2023-02-01 18:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/User.java
> +        return Objects.equals(id, user.id) && Objects.equals(email, user.email) && Objects.equals(name, user.name);
Здесь equals(...) зависит от всех параметров объекта,  а "equals(...)" в БД реализован только с использованием первичного ключа (id). Поэтому возникает несоответствие объектного и реляционного отображений.
Аналогично для остальных моделей.

2023-02-01 18:07 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/bookings/controller/BookingControllerIT.java
> +package ru.practicum.shareit.bookings.controller;
Не исправлено.

2023-02-03 14:05 UTC, NikolaiDem approved these changes

2023-02-03 14:07 UTC, merged